<<<<<<< HEAD:Projects/migrations/0001_initial.py
# Generated by Django 5.2.1 on 2025-06-04 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done'), ('Backlog', 'Backlog')], default='Backlog', max_length=20)),
                ('create_at', models.DateField()),
                ('dealine', models.DateField()),
                ('assignees', models.ManyToManyField(blank=True, related_name='project_assignees', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(default='bạn chưa điền tên', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_repoter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('create_at', models.DateField()),
                ('dealine', models.DateField()),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done'), ('Backlog', 'Backlog')], default='Backlog', max_length=20)),
                ('assignees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Projects.projects')),
            ],
        ),
    ]
=======
# Generated by Django 5.2.1 on 2025-05-31 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done'), ('Backlog', 'Backlog')], default='Backlog', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dealine', models.DateField()),
                ('assignees', models.ManyToManyField(blank=True, related_name='project_assignees', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(default='bạn chưa điền tên', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_repoter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dealine', models.DateField()),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done'), ('Backlog', 'Backlog')], default='Backlog', max_length=20)),
                ('assignees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Projects.projects')),
            ],
        ),
    ]
>>>>>>> quan:Gozic/Projects/migrations/0001_initial.py
