# Generated by Django 5.2.1 on 2025-06-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='InfoPortal.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
