# Generated by Django 5.2.1 on 2025-06-05 14:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ManyToManyField(related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('folder', models.ManyToManyField(related_name='pages', to='InfoPortal.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
