# Generated by Django 5.2.1 on 2025-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
