# Generated by Django 5.2.1 on 2025-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0002_page_modified_at_alter_page_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
