# Generated by Django 5.2.1 on 2025-06-03 18:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0003_remove_page_modified_at_alter_page_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
