# Generated by Django 5.2.1 on 2025-06-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0005_folder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='folder',
        ),
        migrations.AddField(
            model_name='page',
            name='folder',
            field=models.ManyToManyField(related_name='pages', to='InfoPortal.folder'),
        ),
    ]
