# Generated by Django 5.2.1 on 2025-06-04 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0007_alter_page_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ManyToManyField(null=True, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
