# Generated by Django 5.2.1 on 2025-06-04 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0008_remove_folder_user_folder_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ManyToManyField(related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
