# Generated by Django 5.2.1 on 2025-06-11 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_groupmembers_chatgroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_group_member', to='Messenger.chatgroup'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_member_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
