# Generated by Django 5.2.1 on 2025-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_chatgroup_admin_chatgroup_groupchat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='is_group',
            field=models.BooleanField(default=True),
        ),
    ]
