# Generated by Django 5.2.1 on 2025-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_age_account_image_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=18, max_length=20),
            preserve_default=False,
        ),
    ]
