# Generated by Django 5.2.1 on 2025-06-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_age'),
        ('Account', '0005_alter_account_email'),
    ]

    operations = [
    ]
