# Generated by Django 5.2.1 on 2025-05-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='create_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateField(),
        ),
    ]
